REPO_ROOT ?= ../../..
TB_NAME   := tb_mac_resource_dl_builder
TB_SRCS   := tb_mac_resource_dl_builder.v $(REPO_ROOT)/rtl/umac/tetra_mac_resource_dl_builder.v

include $(REPO_ROOT)/tb/rtl/Makefile.inc
